### ISSUE TITLE
Volt exceptions conflicting with HoneyBadger

### ISSUE THREAD

**Issue by cheekyboots** [honeybadger-io/honeybadger-laravel#132]
## What are the steps to reproduce this issue?

1. Use Livewire Volt
2. Have pretty much any coding issue with a Volt component

## What happens?
Honeybadger chokes on: 
vendor/honeybadger-io/honeybadger-laravel/src/ContextManager.php:64

with:
explode(): Argument #2 ($string) must be of type string, Closure given

## What were you expecting to happen?
I'm not sure if you can do something to actually catch these "Closure given" Volt exceptions, they are Symphony ViewExceptions not normal Laravel exceptions, and right now HoneyBadger doesn't catch them. But Telescope does, if HoneyBadager doesn't choke on this one line. 

I fixed it by adding this at the beginning of the function: 

   ```
private function setLaravelRouteActionContext()
    {
		$route = Route::getCurrentRoute()->getActionName();
	    if (gettype($route) === 'object' && get_class($route) === 'Closure') {
			
			$reflection = new ReflectionFunction($route);
		    $className = get_class($reflection->getClosureThis());
						
			if ($className === "Livewire\Volt\VoltManager") {				
				$routeAction = $reflection->getStaticVariables()['componentName'];
				$this->honeybadger->setComponent($routeAction);
				return;
			}
		}
```

**Comment by subzero10** [comment]
Hey @cheekyboots, thanks for submitting an issue!

Can you please help me reproduce this issue? I created a demo app with Livewire and Volt setup. I created a Counter Volt component and the errors seem to be reported on Honeybadger. I'm rendering the Volt component as a full-page component.
![CleanShot 2024-10-03 at 09 56 48@2x](https://github.com/user-attachments/assets/8808b60a-7564-4d9f-ab8c-f62c18bad7c6)

**Comment by cheekyboots** [comment]
Try adding: 

public function mount() {
        $a = $b;
}
    
as per https://github.com/livewire/livewire/discussions/8687 
Sorry, I have mount() in all my components so I didn't realize it was required to create the issue
