### ISSUE TITLE
Changes for EU endpoint

### ISSUE THREAD

**Issue by stympy** [honeybadger-io/honeybadger-laravel#137]
The installer command should have an optional flag that sets the endpoint to https://eu-api.honeybadger.io/ when generating the configuration file. See https://github.com/honeybadger-io/honeybadger-ruby/pull/584 for the similar change that was made to the Ruby gem.

https://github.com/honeybadger-io/honeybadger-laravel/blob/b96932cb21f7bf98e55775746ca83faff7425986/src/Commands/HoneybadgerDeployCommand.php#L51 also needs to be updated to use the EU host instead of being hard-coded to api.honeybadger.io.

**Comment by stympy** [comment]
Perhaps we should add `'endpoint' => env('HONEYBADGER_ENDPOINT')` to https://github.com/honeybadger-io/honeybadger-laravel/blob/master/config/honeybadger.php

**Comment by stympy** [comment]
A customer reported that the "checkins:sync" command does not work, even if the new endpoint is configured.

**Comment by subzero10** [comment]
> A customer reported that the "checkins:sync" command does not work, even if the new endpoint is configured.

Thanks, I created a [ticket](https://github.com/honeybadger-io/honeybadger-php/issues/202) to track this.

**Comment by subzero10** [comment]
Note to me: Update documentation to add a note for configuring the endpoints (App and API url) to use the EU stack.
