### ISSUE TITLE
[Enhancement] Make a artisan deploy command

### ISSUE THREAD

**Issue by riyuk** [honeybadger-io/honeybadger-laravel#25]
I just wondered why there is no `php artisan honeybadger:deploy` command which runs on the server after a deployment. (like in Forge, deployment-scripts)

Is there a easy way to integrate this using the env-variables?

**Comment by joshuap** [comment]
I think an artisan command is a great idea, would this be difficult, @sixlive?

@riyuk in the meantime, it's pretty easy to do deploy notifications from the command line, which might be an option:

```sh
curl --data "deploy[environment]=production&deploy[local_username]=colin&deploy[revision]=12345&deploy[repository]=https://github.com/user/repo.git&api_key=asdf" "https://api.honeybadger.io/v1/deploys"
```
https://docs.honeybadger.io/api/deployments.html

**Comment by sixlive** [comment]
Love this idea! Not too hard at all.

I'm thinking something like:
```bash
php artisan honeybadger:deploy {?rev}
```

If `rev` is undefined we can check for a git tag and fallback to git hash?

**Comment by joshuap** [comment]
Can artisan have multiple flags/arguments? There are a few options you can override in our capistrano integration, for instance:

https://github.com/honeybadger-io/honeybadger-ruby/tree/master/vendor/capistrano-honeybadger

The git revision/repository are automatically read from git if they aren't provided. The local_username also defaults to `whoami` (the user of the current deployer). It may make sense to put these options in the normal config (with the api key, etc.) vs. use artisan arguments to override them. 

Also, there's another feature that could use the revision, if it were available to the rest of the Laravel app. The revision can optionally be sent in the `server` hash of error payloads:

https://docs.honeybadger.io/api/exceptions.html#sample-payload

What do you think?

**Comment by sixlive** [comment]
Yes, it can accept multiple arguments. Some of this stuff is already defined in the config e.g. environment, and version (https://github.com/honeybadger-io/honeybadger-laravel/blob/master/config/honeybadger.php#L12-L13). We do already send the version with the exception. I’m thinking we should use these values by default. I’ll add each parameter as a CLI argument for flexibility.

 I’ll work up something tomorrow.

**Comment by riyuk** [comment]
I am currently using a custom route with:
```php
$client = new \GuzzleHttp\Client();
    $commitHash = trim(exec('git log --pretty="%h" -n1 HEAD'));
    $response = $client->request('POST', 'https://api.honeybadger.io/v1/deploys?' .
'deploy[environment]=production&deploy[local_username]=&deploy[repository]=git@bitbucket.org:xyz.git&' .
        'deploy[revision]='.$commitHash.'&' .
        'api_key=abcde')->getBody();
```
but i just thought it would be smarter to integrate that in my deployment script instead of triggering a url-request to the custom domain :)

**Comment by sixlive** [comment]
I still need to do a final production test but here is the purposed implementation https://github.com/honeybadger-io/honeybadger-laravel/pull/26.

**Comment by riyuk** [comment]
This would still be a interesting feature. It seems like Laravel Forge don't like Webhooks which triggers after a deployment on the same server/ same domain.

**Comment by sixlive** [comment]
@riyuk Deployed with [v1.6.0](https://github.com/honeybadger-io/honeybadger-laravel/releases/tag/v1.6.0)
