### ISSUE TITLE
Error suppresion with @ doesn't seem to work

### ISSUE THREAD

**Issue by riyuk** [honeybadger-io/honeybadger-laravel#27]
## What are the steps to reproduce this issue?
Tinker:
`Auth::loginUsingId(1)`

## What happens?
I get tons of Errors like `unlink(/home/forge/abc/storage/framework/sessions/NfkuYxmlk3ZjVy0wirhi2uqsZsIYajEyLJlI61Yk): No such file or directory`

## What were you expecting to happen?
No errors - since errors get suppresed with `@`!
See: https://github.com/laravel/framework/blob/5.8/src/Illuminate/Filesystem/Filesystem.php#L207

## Any other comments?
See:
https://github.com/laravel/framework/issues/22514

## What versions are you using?
**Operating System:** PHP 7.2 fpm
**Package Version:** 1.5.0

**Comment by sixlive** [comment]
I believe this is caught and reported by the global error handler. I'll take a look at this over the weekend.

**Comment by riyuk** [comment]
Hi @sixlive,
is there any progress?

Also i get Errors like this:
`unserialize(): Error at offset 0 of 63 bytes`
from a line where i shouldnt get this:
`$this->recaller = @unserialize($recaller, ['allowed_classes' => false]) ?: $recaller;` in `/home/forge/abc.de/vendor/laravel/framework/src/Illuminate/Auth/Recaller.php:24:in `handle'`

**Comment by sixlive** [comment]
I don’t think this has anything to do with the library we simply register an optional global error handler. I believe this needs to be resolved through your PHP engine error settings.

**Comment by sixlive** [comment]
I might have an idea, I’ll try and write a test for it today

**Comment by sixlive** [comment]
Is there any way you can get me your current php settings so I can ensure we are testing the same thing?

**Comment by riyuk** [comment]
I think there need to be done a check if the Error-Code is 0. (at least that's my guess)
```php
if (0 === $code) {
    return false;
}
```
Since PHP will report that Error to a Custom Error Handler - regardless of configuration.
Quote:

> If you have set a custom error handler function with set_error_handler() then it will still get called, but this custom error handler can (and should) call error_reporting() which will return 0 when the call that triggered the error was preceded by an @.
See: https://www.php.net/manual/en/language.operators.errorcontrol.php

So I think it's the job of HoneyBadger-PHP right here:
https://github.com/honeybadger-io/honeybadger-php/blob/master/src/Handlers/ErrorHandler.php#L34
to first check, if that error is worth reporting or if the User marked that line as suppressed with an `@`.

At least that's what I am understanding :)

**Comment by sixlive** [comment]
100% what I’m thinking too. I have something worked up just need to finish testing

**Comment by sixlive** [comment]
I've opened https://github.com/honeybadger-io/honeybadger-php/pull/83 to address this.

**Comment by sixlive** [comment]
@riyuk tagge in [honeybadger-io/honeybadger-php@1.5.1](https://github.com/honeybadger-io/honeybadger-php/releases/tag/v1.5.1)

**Comment by riyuk** [comment]
@sixlive can you also publish 1.5.1 to packagist? :)

**Comment by sixlive** [comment]
@riyuk There seems to be an issue getting it over to packagist, I dont have admin access to that account but I'm working with the team to get that fixed.

**Comment by sixlive** [comment]
@riyuk I just verified that it’s now published to packagist.

**Comment by riyuk** [comment]
Hey.
https://packagist.org/packages/honeybadger-io/honeybadger-laravel still displays 1.5.0 as current version.

**Comment by sixlive** [comment]
The patch was part of honeybader-php
