### ISSUE TITLE
Call to undefined method Laravel\Lumen\Routing\Router::getCurrentRoute()

### ISSUE THREAD

**Issue by pjona** [honeybadger-io/honeybadger-laravel#39]
## What are the steps to reproduce this issue?

1. Install Lumen 6 app
2. Enable Lumen integration with `Identifying Users`
3. Visit any route

## What happens?
```
[2019-09-19 09:12:54] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Laravel\Lumen\Routing\Router::getCurrentRoute() in /var/www/vendor/illuminate/support/Facades/Facade.php:239
Stack trace:
#0 /var/www/vendor/honeybadger-io/honeybadger-laravel/src/Middleware/HoneybadgerContext.php(43): Illuminate\Support\Facades\Facade::__callStatic('getCurrentRoute', Array)
#1 /var/www/vendor/honeybadger-io/honeybadger-laravel/src/Middleware/HoneybadgerContext.php(35): Honeybadger\HoneybadgerLaravel\Middleware\HoneybadgerContext->setRouteActionContext()
#2 /var/www/vendor/illuminate/pipeline/Pipeline.php(171): Honeybadger\HoneybadgerLaravel\Middleware\HoneybadgerContext->handle(Object(Laravel\Lumen\Http\Request), Object(Closure))
#3 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Laravel\Lumen\Http\Request))
#4 /var/www/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Laravel\Lumen\Http\Request))
#5 /var/www/vendor/illuminate/pipeline/Pipeline.php(105): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Laravel\Lumen\Http\Request))
#6 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(413): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#7 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(171): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#8 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(108): Laravel\Lumen\Application->dispatch(NULL)
#9 /var/www/public/index.php(28): Laravel\Lumen\Application->run()
#10 {main} {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method Laravel\\Lumen\\Routing\\Router::getCurrentRoute() at /var/www/vendor/illuminate/support/Facades/Facade.php:239)
```

## What were you expecting to happen?
No exception

## Any other comments?
Looks like Lumen is using `nikic/fast-route` package and not Illuminate one.
I made quick three changes in `HoneybadgerContext` class:
- Pass `$request` variable to `setRouteActionContext()` function,
- `Route::getCurrentRoute()` -> `app()->router->getRoutes()[$request->method() . $request->getPathInfo()]`,
- `Route::getCurrentRoute()->getActionName()` -> `app()->router->getRoutes()[$request->method() . $request->getPathInfo()]['action']['uses']`

And then it's working. What would be perfect solution for this problem?
1. Create new Middleware for Lumen with above changes?
2. Somehow detect if a user is using Laravel or Lumen integration and use the correct function?

## What versions are you using?
**Package Version:** 1.7.2

**Comment by sixlive** [comment]
Thank you for the thorough report. I will address this today.

**Comment by sixlive** [comment]
Tracking https://github.com/honeybadger-io/honeybadger-laravel/pull/42 for this fix. Just want to do some more testing. Will cut a patch for it today.
