### ISSUE TITLE
Laravel schedule onSuccess hook

### ISSUE THREAD

**Issue by smknstd** [honeybadger-io/honeybadger-laravel#47]
Laravel now has [onSuccess hook](https://laravel.com/docs/5.8/scheduling#task-hooks) so maybe there should be a macro to ping honeybadger only when task succeed:

```
        Event::macro('thenPingHoneybadger', function ($id) {
            return $this->then(function () use ($id) {
                app(Reporter::class)->checkin($id);
            });
        });
```

**Comment by sixlive** [comment]
@smknstd Love the suggestion! Tracking the implementation on https://github.com/honeybadger-io/honeybadger-laravel/pull/49
