### ISSUE TITLE
Laravel 7 support

### ISSUE THREAD

**Issue by damcclean** [honeybadger-io/honeybadger-laravel#53]
Hey, I'm planning on updating my Laravel apps to Laravel 7 which was released a few hours ago but looking at the composer file, it looks like the it depends on 6.0 of Laravel packages.

Hopefully this is an easy enough thing to do - let me know if you'd like me to try and pull request an upgraded `composer.json` file for you 😄

**Comment by stympy** [comment]
Thanks for asking! :) Please do try it -- we'd be happy to accept a PR.

**Comment by sixlive** [comment]
Would welcome a PR but should have it set sometime this evening or tomorrow!

**Comment by damcclean** [comment]
Alright, opened #54.

**Comment by stympy** [comment]
@damcclean Feel free to hit me up at support@honeybadger.io to get a t-shirt as a thank-you. 😀
