### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by osbre** [honeybadger-io/honeybadger-laravel#63]
Note: Laravel 8 already has PHP 8 support.

## Possible solution

1. Modify `composer.json` :

`"php": "^7.3|^8.0",`

And check if the tests are passed.

2. Add PHP 8 to GitHub Actions Workflow

https://github.com/honeybadger-io/honeybadger-laravel/blob/master/.github/workflows/run-tests.yml#L13

**Comment by sixlive** [comment]
Released [v3.3.0](https://github.com/honeybadger-io/honeybadger-laravel/releases/tag/v3.3.0)

**Comment by osbre** [comment]
Thank you!
