### ISSUE TITLE
Document generating a new Laravel app w/ Honeybadger

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-laravel#67]
We currently have an [example Laravel app w/ Honeybadger](https://github.com/honeybadger-io/crywolf-laravel). Example apps are difficult to maintain, though; they need to be kept up to date, upgraded when new Laravel versions are released, etc. I'd rather have a playbook for how to generate an example Laravel app w/ Honeybadger.

This is an exploration issue—take a look at the current crywolf-laravel example app, and then try creating a new Laravel app from the official Laravel docs and our [Laravel integration guide](https://docs.honeybadger.io/lib/php/integration/laravel.html). Add a single controller to the app with a failing action.

Document the process (in markdown) here so that I can reproduce it myself. :) Also, please include instructions for setting up a super simple Laravel development environment on macOS (or you could link to some existing documentation). The final result should be a short guide (similar to the Laravel getting started docs) for how to take a fresh Mac and create a boilerplate example app w/ Honeybadger.

**Comment by shalvah** [comment]
Hmm, I don't know if the focus on "generating a new app" is the way to go. Might be extrapolating a bit, but I think devs typically come from their Laravel app to the error tracker or any extra services, and not the other way round — they already know how to create a new Laravel app (or can easily look it up), so the major concern is "how do I get error tracking into this app I already have?" IMO, it's better to focus on making the integration as easy as possible (and a lot of good work has already been done there).

Speaking of the integration process, some feedback there: Laravel has changed things a bit, so the current Laravel guide is a bit out of date for newer releases. The old method still works (because the exception handler code was changed in a minor release), but it would be worth updating to avoid new user confusion.

Also, the last step of the onboarding (https://app.honeybadger.io/first_run/install_code#laravel) looks like this:

![image](https://user-images.githubusercontent.com/14361073/107937695-8f91df00-6f84-11eb-8bfe-41120bca4ba1.png)

As a new user, I was a bit stumped as to what the `0...c` at the end of the command meant, and what was being waited for, before I eventually realised it's probably my API key and it's going to send a test exception. It would be better if the page 's intro had stated, "We'll walk you through setting up and sending a test exception." The last instruction would also have been better with a _why_ component: "Finally, run the honeybadger:install artisan command, passing in your API key. This will set up your env variables and config file, and send a test exception to make sure everything works okay."

Re getting started on macOS, how about using [Laravel Sail](https://laravel.com/docs/8.x/installation#getting-started-on-macos)? It's Docker-based, so you should only need to run a script to have everything up.

**Comment by shalvah** [comment]
Some more setup feedback: there's a convention in Laravel of adding descriptive comments in config files, both in the framework and external packages. For instance, here's the `app.php` file in every Laravel project:

![image](https://user-images.githubusercontent.com/14361073/107938971-640ff400-6f86-11eb-860b-b0c35c1b8d58.png)

The comments provide inline bite-size docs that give users context on what the options mean and why you might want to set them.

By contrast, the current Honeybadger config file is pretty barebones. 

![image](https://user-images.githubusercontent.com/14361073/107939119-97eb1980-6f86-11eb-8f91-4cfc5ffe2913.png)


Would be helpful to follow the convention and add descriptive comments (eg for `version`: "Adding a version allows Honeybadger to do X". Also, the commented-out code is part of the published config file, and that's a bit confusing for a new user — why's it there? Is it safe to remove it?, etc.

**Comment by joshuap** [comment]
> Hmm, I don't know if the focus on "generating a new app" is the way to go. Might be extrapolating a bit, but I think devs typically come from their Laravel app to the error tracker or any extra services, and not the other way round — they already know how to create a new Laravel app (or can easily look it up), so the major concern is "how do I get error tracking into this app I already have?" IMO, it's better to focus on making the integration as easy as possible (and a lot of good work has already been done there).

Ah, I should have clarified this better. This issue is primarily *for me*, because I always forget this, and I want to personally run through the process so that I can review the onboarding process more frequently. 😂 Also, I want to document this information internally for each of our integrations so that I can eventually hand that doc to someone (a junior dev, QA, etc.) and say "here, run through this and take notes."

I agree that we don't need to provide this level of detail for users.

> Speaking of the integration process, some feedback there: Laravel has changed things a bit, so the current Laravel guide is a bit out of date for newer releases. The old method still works (because the exception handler code was changed in a minor release), but it would be worth updating to avoid new user confusion.
> 
> Also, the last step of the onboarding (https://app.honeybadger.io/first_run/install_code#laravel) looks like this:
> 
> ![image](https://user-images.githubusercontent.com/14361073/107937695-8f91df00-6f84-11eb-8bfe-41120bca4ba1.png)
> 
> As a new user, I was a bit stumped as to what the `0...c` at the end of the command meant, and what was being waited for, before I eventually realised it's probably my API key and it's going to send a test exception. It would be better if the page 's intro had stated, "We'll walk you through setting up and sending a test exception." The last instruction would also have been better with a _why_ component: "Finally, run the honeybadger:install artisan command, passing in your API key. This will set up your env variables and config file, and send a test exception to make sure everything works okay."

Awesome, this kind of feedback is very appreciated. This ties in with this issue, too, because the main goal here is to fix any inconsistencies in the setup/onboarding process, and improve the PHP/Laravel experience in Honeybadger,

> Re getting started on macOS, how about using [Laravel Sail](https://laravel.com/docs/8.x/installation#getting-started-on-macos)? It's Docker-based, so you should only need to run a script to have everything up.

Yep, that's good!

**Comment by joshuap** [comment]
> Some more setup feedback: there's a convention in Laravel of adding descriptive comments in config files, both in the framework and external packages. For instance, here's the `app.php` file in every Laravel project:
> 
> ![image](https://user-images.githubusercontent.com/14361073/107938971-640ff400-6f86-11eb-860b-b0c35c1b8d58.png)
> 
> The comments provide inline bite-size docs that give users context on what the options mean and why you might want to set them.
> 
> By contrast, the current Honeybadger config file is pretty barebones.
> 
> ![image](https://user-images.githubusercontent.com/14361073/107939119-97eb1980-6f86-11eb-8f91-4cfc5ffe2913.png)
> 
> Would be helpful to follow the convention and add descriptive comments (eg for `version`: "Adding a version allows Honeybadger to do X". Also, the commented-out code is part of the published config file, and that's a bit confusing for a new user — why's it there? Is it safe to remove it?, etc.

I think it would be good to add documentation to the config file. I believe the commented out version thing is an example of how to automatically set the version from git. Perhaps that could be part of the documentation comment for `version`?

@sixlive do you have anything to add?

**Comment by shalvah** [comment]
@joshuap i'm not sure if you meant "here" here, but here goes😅. We can move this guide to a better place if needed.


Here's a guide for setting up and testing Honeybadger features in a fresh Laravel app:

## Setting up error tracking

1. Set up a dev environment.
   a. If you'd rather not set up a PHP dev environment, you can use a Docker-based approach instead. You'll need to have Docker installed.
   b. If you're fine with setting up a PHP environment, you'll need to install PHP (7.4 or 8.x). Then [install Composer](https://getcomposer.org/doc/00-intro.md).

2. Create a new Laravel app (let's call it `example-honeybadger-app`).
   - Docker: use [Laravel Sail](https://laravel.com/docs/8.x/installation#your-first-laravel-project): `curl -s https://laravel.build/example-honeybadger-app | bash`.
   - Non-Docker: [install with Composer](https://laravel.com/docs/8.x/installation#installation-via-composer): `composer create-project laravel/laravel example-honeybadger-app`.

3. Install Honeybadger (from within the project directory):
   - Docker: `sail composer require honeybadger-io/honeybadger-laravel`
   - Non-Docker: `composer require honeybadger-io/honeybadger-laravel`

4. Add the Honeybadger exception handler: In the `register()` function of `app/Exceptions/Handler.php`, add this:
   ```php
   
   $this->reportable(function (Throwable $e) {
       if (app()->bound('honeybadger')) {
           app('honeybadger')->notify($e, app('request'));
       }
   });
   ```

5. Run the Honeybadger install command to set up your env variables, publish your config file and send a test event:
   - Docker: `sail artisan honeybadger:install <your-api-key>`.
   - Non-Docker: `php artisan honeybadger:install <your-api-key>`.

## Adding a route that throws an exception
1. Edit the `Route::get` route in `routes/web.php` so it looks like this:
   ```php
   Route::get('/', function () {
      throw new \Exception("Oh no!");
      return view('welcome');
   });
   ```
2. Start the app and then visit it on the provided url. An exception should be rendered in the browser and reported to Honeybadger.
   - Docker: `./vendor/bin/sail up` (http://localhost/)
   - Non-Docker: `php artisan serve` (http://127.0.0.1:8000)

3. You can also add the middleware for user and route context: in `app/Http/Kernel.php`, add the `HoneybadgerContext` to the "web" array in `$middlewareGroups` :

   ```php
   protected $middlewareGroups = [
    'web' => [
       // ... other middleware
        \Honeybadger\HoneybadgerLaravel\Middleware\HoneybadgerContext::class,
      ]
   ];
   ```

**Comment by joshuap** [comment]
This worked well for me, thanks. :) I've copied it into our handbook so that we can repeat this process whenever we need a new laravel app for testing.

**Comment by shalvah** [comment]
To use a local version of the package inside your Laravel app:

- Add a `repositories` entry to your `composer.json` that points to the local package path:
```
    "repositories": [
        {
            "type": "path",
            "url": "../../Honeybadger/honeybadger-laravel"
        }
    ],
```

- Modify the version constraint for the package in the `require` section of `composer.json`:
```
"honeybadger-io/honeybadger-laravel": "@dev",
```

- Run `composer update`. You should see some output like this:
```
Installing honeybadger-io/honeybadger-laravel (dev-user-informer): Junctioning from ../../Honeybadger/honeybadger-laravel
```

Now, any changes or Git updates you make to the base package should be used in the Laravel app.

**Comment by joshuap** [comment]
I had to modify docker-compose.yml to make this work w/ Sail:

```diff
16        volumes:
17           - '.:/var/www/html'
+18           - '~/Code/honeybadger-io/honeybadger-laravel:/honeybadger-laravel'
```

then update composer.json like this:

```json
 "repositories": [
        {
            "type": "path",
            "url": "/honeybadger-laravel"
        }
    ],
```
