### ISSUE TITLE
Automatic Laravel breadcrumbs

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-laravel#77]
This issue depends on https://github.com/honeybadger-io/honeybadger-php/issues/140.

Once we have the API for adding breadcrumbs, we can add some types of breadcrumbs automatically for Laravel. [Here are the docs](https://docs.honeybadger.io/lib/ruby/getting-started/breadcrumbs.html#automatic-rails-breadcrumbs) on the types of breadcrumbs we automatically collect in Rails (read the whole guide for ideas).

Let's start a list of things we'd like to instrument in Laravel (feel free to add to this):

- [ ] [Log messages](https://laravel.com/docs/8.x/logging)

**Comment by shalvah** [comment]
I'm thinking:
- Blade render calls
- SQL queries
- Redis queries
- Notification dispatches
- Email dispatches
- Job dispatches

**Comment by joshuap** [comment]
Is there a way to hook into controller actions to report a breadcrumb when one is called? We have these in Rails:

https://github.com/honeybadger-io/honeybadger-ruby/blob/master/lib/honeybadger/breadcrumbs/active_support.rb#L68

Also cache read/hit breadcrumbs may be useful if Laravel has built-in caching.

**Comment by shalvah** [comment]
AFAIK, Laravel doesn't provide an official way to hook into controller events, but I think it should be doable, thanks to the way the framework is written.

Yep, cache comes with Laravel (I mentioned Redis in my earlier comment😅), so that can be done.

**Comment by shalvah** [comment]
Closed in #79
