### ISSUE TITLE
Include controller and action name in request data

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-laravel#8]
## What are the steps to reproduce this issue?

1. Generate error with https://github.com/honeybadger-io/crywolf-laravel
2. Review error report in Honeybadger

## What happens?
The error is reported, but the controller and action name aren't included. This data can help with error grouping as well as quickly identifying the location of the error in your app.

## What were you expecting to happen?
In a Rails app, if an error happens while processing the `UsersController#create` action, for example, then in Honeybadger it will show `users#index` in the list. That data is sent in the notice payload at `notice['request']['component']` and `notice['request']['action']`, respectively:

https://github.com/honeybadger-io/honeybadger-ruby/blob/master/lib/honeybadger/notice.rb#L334

## What versions are you using?
**Operating System:** Linux
**Package Version:** 1.1.0

**Comment by sixlive** [comment]
Added in https://github.com/honeybadger-io/honeybadger-laravel/pull/31 and https://github.com/honeybadger-io/honeybadger-php/releases/tag/v1.7.0
