### ISSUE TITLE
Configurable development environments

### ISSUE THREAD

**Issue by bilogic** [honeybadger-io/honeybadger-laravel#83]
From https://docs.honeybadger.io/lib/ruby/getting-started/environments.html

> Some environments should usually not report errors at all, such as when you are developing on your local machine...

Can we have this specified in Laravel's config file please?

I'm happy to write the code, but able to let me know where is good place to store this option?
The current `environment` key can be confusing as it is referring to variables.

**Comment by joshuap** [comment]
@bilogic that looks like a Ruby docs link—I don't believe we have the development environments feature in PHP (although it might be a nice addition in the future). According to our PHP docs, Honeybadger reports errors in all environments unless there is no API key configured:

https://docs.honeybadger.io/lib/php/guides/environments.html

@sixlive @shalvah does that sound right? Thoughts on adding a `development_environments` option, similar to the Ruby gem?

**Comment by bilogic** [comment]
@joshuap yea it is a Ruby link. But I thought it would be useful since there is little reason to track exceptions in development environments. Thank you.

**Comment by shalvah** [comment]
I agree with the general idea, but I'm reluctant to add another config option. Perhaps we can repurpose the existing [`report_data`](https://docs.honeybadger.io/lib/php/reference/configuration.html) item (I don't think it's documented properly, but that's what it's for, right?)?

Then we could just have the default config file be like:

```
report_data => app()->environment("production"),
```

@bilogic can you try this out and see if it works?

**Comment by bilogic** [comment]
@shalvah 

Do you mean we whitelist the environments to report for only? Is it better as an array?
Why not blacklist like Ruby? Then you guys just have to document once. :)

**Comment by shalvah** [comment]
I'm saying there's already a `report_data` option which achieves the same thing, and I don't think we should be adding a new one (and documenting both).

Whitelist or blacklist, you can achieve whichever you prefer with that option:

```
// Report on production and staging only
"report_data" => app()->environment(["production", "staging"]),

// Report everywhere except development and testing
"report_data" => !app()->environment(["development", "testing"]),
```

**Comment by bilogic** [comment]
> ```
> // Report everywhere except development and testing
> "report_data" => !app()->environment(["development", "testing"]),
> ```

Ok thanks, let me test it out. I didn't know you could write that way.

**Comment by shalvah** [comment]
Sure thing. It's not my preferred API, but there's a cost to adding every new config item, especially when what it does is already covered.

**Comment by basepack** [comment]
Was looking for exact the same thing, maybe add this to the Laravel docs? 

This code example:
```
// Report on production and staging only
"report_data" => app()->environment(["production", "staging"]),

// Report everywhere except development and testing
"report_data" => !app()->environment(["development", "testing"]),
```

**Comment by joshuap** [comment]
> I agree with the general idea, but I'm reluctant to add another config option. Perhaps we can repurpose the existing [`report_data`](https://docs.honeybadger.io/lib/php/reference/configuration.html) item (I don't think it's documented properly, but that's what it's for, right?)?
> 
> Then we could just have the default config file be like:
> 
> ```
> report_data => app()->environment("production"),
> ```

I'm OK with this, although I'm also not opposed to adding an additional `development_environments` option, like we do for Ruby (where we have both). [The way we explain it there](https://docs.honeybadger.io/lib/ruby/getting-started/environments.html#development-environments) is that "these are the environments where Honeybadger doesn't report errors" if you want to ignore that feature, override it with `report_data => true`. Since we provide a default config for Laravel, I do appreciate the idea of explicitly configuring `report_data` based on the environment—if we go that route, I prefer this default:

```
// Report everywhere except development and testing
"report_data" => !app()->environment(["development", "testing"]),
```

**Comment by shalvah** [comment]
Yup, I'll add it to the default Laravel config.

**Comment by shalvah** [comment]
Ah, turns out `"report_data" => !app()->environment(["development", "testing"]),` does not work because the environment() helper is only available after the config is loaded. This works instead:

```
    "report_data" => !in_array(env('APP_ENV'), ["local", "testing"]),
```

**Comment by joshuap** [comment]
It would be great if we could put the "report_data" environment option right below the "environment" option, since their default config will be related.

**Comment by shalvah** [comment]
Added `report_data` to default config (defaults to ignoring local/test). It'll ignore the setting when you're sending a test exception, but it'll inform you about it.

```
You have `report_data` set to false in your config. Errors won't be reported in this environment.
We've switched it to true for this test, but you should check that it's enabled for your production environments.
```


Docs: https://github.com/honeybadger-io/docs/pull/105
