### ISSUE TITLE
Identify application frames in backtrace

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-laravel#9]
On Laravel's error debug page, which you can see if you generate a test error in [crywolf-laravel](https://github.com/honeybadger-io/crywolf-laravel) with debug enabled, you can toggle between the "application frames" and "all frames":

![image](https://user-images.githubusercontent.com/474649/44177489-0d6a8c00-a0a3-11e8-869d-5564f3265ce1.png)

Rails has the same concept of an "application trace", and it's something we rely heavily on when displaying traces in Honeybadger.

Laravel uses [`whoops`](https://github.com/filp/whoops) to display its debug page, and `whoops` identifies which frames belong to the application using the concept of "application paths", which is an array of paths that application files will start with. Each framework which uses `whoops` can configure its own unique application paths using the `setApplicationPaths` function:

https://github.com/filp/whoops/blob/e79cd403fb77fc8963a99ecc30e80ddd885b3311/src/Whoops/Handler/PrettyPageHandler.php#L663

Laravel configures this value using its own base path, excluding the vendor directory:

https://github.com/laravel/framework/blob/8d39ed08e8745d9f2fc803a85239aa3eaf8ece1c/src/Illuminate/Foundation/Exceptions/WhoopsHandler.php#L35

With those two pieces of information, they can identify which frames in a stack trace are application code and which are core PHP or vendor code.

I think we're already pretty close to being able to approximate this; we have the `project_root` config option in [honeybadger-php](https://github.com/honeybadger-io/honeybadger-php#configuration), which I assume in a Laravel project is set to Laravel's base path (this is how we do it for Rails). That gets us most of the way there, because we can compare each frame to the `project_root` to identify it as belonging to the application. The only remaining issue is that Laravel stores framework files under the `vendor/` path inside of its base path, so we need a way for `honeybadger-laravel` to tell `honeybadger-php` to exclude those lines (which is what `whoops` uses its "application paths" option for).

I see two approaches to this:

1. We could add an API to `honeybadger-php` to allow `honeybadger-laravel` to configure a regexp or some kind of filter to identify which frames within the `project_root` belong to an application (this assumes that all application paths share a common root).
2. We could copy the approach in `whoops`, and add an "application paths" array of our own to `honeybadger-php` (which could default to the `project_root` setting, I guess), then we could configure that value from `honeybadger-laravel` in the same way that Laravel does.

I think I am learning towards option 1 because it introduces fewer new concepts into the system (we already have the concept of a single "project root", but not the concept of "application paths").

Anyway, once we have the ability to identify application frames, [our API schema](https://gist.github.com/joshuap/94901ba378fd09a783be#file-notices-json-L82) already supports the `context` property for that:

```json
{
  "file": "/path/to/file.php",
  "number": "3",
  "method": "functionName",
  "context": "app"
}
```

**Comment by sixlive** [comment]
@joshuap to clarify here, you have support for it in the API by sending `context` with the backtrace. So if I add `app` you will be able to filter accordingly?

**Comment by joshuap** [comment]
@sixlive that's right -- you can add `"context": "app"` to the lines of the backtrace that belong to the application, and our UI will filter it correctly.

**Comment by joshuap** [comment]
I forget if the Laravel side of this still needed work. I've made a personal task to test it out and see if there are any additional improvements to be made.

**Comment by joshuap** [comment]
I've confirmed this is working (and fixed a UI bug :)).
