### ISSUE TITLE
Suggestions for check-in

### ISSUE THREAD

**Issue by bilogic** [honeybadger-io/honeybadger-laravel#92]
Hi,

This isn't a bug, more like a suggestion from using check-ins on success.
Let me try to explain my difficulty then the proposed changes

1. I have trouble telling when a check-in started, especially for long running jobs with variable delays
2. My job typically takes 15 mins, but can be up to 50 mins. I set the grace period to be 30 mins
3. My suggestion is to ping twice and record the check-in and check-out time
4. This way, we know when a job started and how long it took
5. Since there are 2 times now, grace period measures if the job started on time, my tolerance would typically be 1-3 mins
6. Introduce a new term `execution` period, this measures how long the job should typically run for and can probably be optional
7. If check-in started within the grace period, that is `reporting` (as per current)
8. If check-out exceeded `execution` period, that would be `overrun`
9. If check-in did not happen within the grace period, that is `missing` (as per current)
10. Check-ins that fall outside expected start times and grace periods will be `unexpected`

Great work for this very useful tool!

**Comment by joshuap** [comment]
@bilogic thanks for the input! I've saved this to our internal ideas board. The check-ins feature is fairly stable at the moment, but we'll definitely consider this if we plan any big changes in the future.
