### ISSUE TITLE
PHP 8.1 deprecation warnings

### ISSUE THREAD

**Issue by rabidpraxis** [honeybadger-io/honeybadger-laravel#95]
We had a customer reach out about receiving deprecation warnings after upgrading to PHP 8.1:

```
str_replace(): Passing null to parameter #1 ($search) of type array|string is deprecated

Trace
/var/www/app/Exceptions/Handler.php:45:in `notify`
/var/www/public/index.php:52:in `handle`
```

And:

```
explode(): Passing null to parameter #2 ($string) of type string is deprecated

Trace
/var/www/app/Exceptions/Handler.php:45:in `notify`
/var/www/public/index.php:52:in `handle`
```

**Comment by aburany** [comment]
Thanks, Kevin for raising this. To give more context: I updated to PHP 8.1.2 (from 8.0.x) and started getting these issues (one each) after each actual bug reported by Honeybadger. So funnily, Honeybadger is reporting errors from within its own library as well :)

PHP 8.1 has a lot of deprecations, my guess is that the honeybadger-laravel package needs to be made compatible with 8.1.

**Comment by shalvah** [comment]
Right, already did that for the base PHP package, but might have missed a few for the Laravel one. Are you on the latest version?

**Comment by aburany** [comment]
I'm on honeybadger-laravel 3.13.0 and PHP 8.1.2

**Comment by shalvah** [comment]
Welp, just realised I forgot to tag that release.  Try updating the base Honeybagder package:

```
composer update honeybadger-io/honeybadger-php
```

**Comment by aburany** [comment]
Thank you, it's fixed now!
